### ISSUE TITLE
Is it possible to use this with vanilla Fulcro (not headless)?

### ISSUE THREAD

**Issue by joshcho** [matterandvoid-space/subscriptions#34]
As in title. The fulcro example in the examples directory seems to be missing things (like `reactive` looks incomplete).

**Comment by joshcho** [comment]
I see that you removed any integration with Fulcro UI in https://github.com/matterandvoid-space/subscriptions/commit/637471af49267d5ecfdd5ac0cec4b15447ebb405. Will the Fulcro UI use case not be supported? If so, I think it would be nice for new users to see that somewhere.

**Comment by dvingo** [comment]
Hi @joshcho that was my original hope/goal, but I could not figure out how to make it work; furthermore after many years of struggling with fulcro's UI layer I now strongly disadvise its use. 
I have fully embraced the react hooks based approach, using fulcro only for state management. 

I will update the docs to indicate that there is no support for fulcro UI components.

That all being said, if that feature provides utility to others I don't think there is much harm if someone else wants to contribute that feature, so would be open to contributions implementing that.

**Comment by dvingo** [comment]
https://github.com/matterandvoid-space/subscriptions/commit/1cf6c89d1c61c2514415e05c0d8449ce92f3565c
